rootProject.name = "AndroidTechSample"
include(":app")
include(":feature:composable")
include(":feature:core")
include(":feature:biometric")
include(":feature:resources")
include(":feature:groupie")
include(":feature:material")
include(":composeapp")
include(":core:designsystem")
