rootProject.name = "AndroidTechSample"
include(":app")
include(":feature:compose")
include(":feature:core")
include(":feature:biometric")
include(":feature:resources")
include(":feature:groupie")
include(":feature:ameba:followfeed")
include(":feature:twitter:home")
include(":feature:twitter:core")
