package com.messi.designsystem.digitalagency

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class DigitalAgencyColorPalette(
  val backgroundPrimary: Color,
  val backgroundSecondary: Color,
  val backgroundTertiary: Color,
  val textBody: Color,
  val textDescription: Color,
  val textPlaceHolder: Color,
  val textOnFill: Color,
  val textLink: Color,
  val textHover: Color,
  val textActive: Color,
  val textVisited: Color,
  val textAlert: Color,
  val textDisabled: Color,
  val iconLabel: Color,
  val iconActive: Color,
  val iconAlert: Color,
  val iconDisabled: Color,
  val buttonNormal: Color,
  val buttonHover: Color,
  val buttonActive: Color,
  val buttonDisabledBG: Color,
  val borderField: Color,
  val borderDivider: Color,
  val borderFocused: Color,
  val borderSelected: Color,
  val borderAlert: Color,
  val borderDisabled: Color,
  val statusSuccess: Color,
  val statusAlert: Color,
  val statusWarning: Color,
  val chartPrimary: Color,
  val chartSecondary: Color
)

val lightDigitalAgencyColorPalette = DigitalAgencyColorPalette(
  backgroundPrimary = DigitalAgencyPrimitiveColor.white,
  backgroundSecondary = DigitalAgencyPrimitiveColor.Sumi100,
  backgroundTertiary = DigitalAgencyPrimitiveColor.Sumi50,
  textBody = DigitalAgencyPrimitiveColor.Sumi900,
  textDescription = DigitalAgencyPrimitiveColor.Sumi700,
  textPlaceHolder = DigitalAgencyPrimitiveColor.Sumi600,
  textOnFill = DigitalAgencyPrimitiveColor.white,
  textLink = DigitalAgencyPrimitiveColor.Sea800,
  textHover = DigitalAgencyPrimitiveColor.Sea600,
  textActive = DigitalAgencyPrimitiveColor.Sea900,
  textVisited = DigitalAgencyPrimitiveColor.Sea900,
  textAlert = DigitalAgencyPrimitiveColor.Sun800,
  textDisabled = DigitalAgencyPrimitiveColor.Sumi500,
  iconLabel = DigitalAgencyPrimitiveColor.Sumi900,
  iconActive = DigitalAgencyPrimitiveColor.Sea800,
  iconAlert = DigitalAgencyPrimitiveColor.Sun800,
  iconDisabled = DigitalAgencyPrimitiveColor.Sumi500,
  buttonNormal = DigitalAgencyPrimitiveColor.Sea800,
  buttonHover = DigitalAgencyPrimitiveColor.Sea800.copy(alpha = 0.13f),
  buttonActive = DigitalAgencyPrimitiveColor.Sea800.copy(alpha = 0.13f),
  buttonDisabledBG = DigitalAgencyPrimitiveColor.Sumi500,
  borderField = DigitalAgencyPrimitiveColor.Sumi900,
  borderDivider = DigitalAgencyPrimitiveColor.Sumi300,
  borderFocused = DigitalAgencyPrimitiveColor.Wood600,
  borderSelected = DigitalAgencyPrimitiveColor.Sea800,
  borderAlert = DigitalAgencyPrimitiveColor.Sun800,
  borderDisabled = DigitalAgencyPrimitiveColor.Sumi300,
  statusSuccess = DigitalAgencyPrimitiveColor.Forest600,
  statusAlert = DigitalAgencyPrimitiveColor.Sun800,
  statusWarning = DigitalAgencyPrimitiveColor.Wood800,
  chartPrimary = DigitalAgencyPrimitiveColor.Sea800,
  chartSecondary = DigitalAgencyPrimitiveColor.Sea400,
)
val darkDigitalAgencyColorPalette = DigitalAgencyColorPalette(
  backgroundPrimary = DigitalAgencyPrimitiveColor.Sumi900,
  backgroundSecondary = DigitalAgencyPrimitiveColor.Sumi700,
  backgroundTertiary = DigitalAgencyPrimitiveColor.Sumi800,
  textBody = DigitalAgencyPrimitiveColor.white,
  textDescription = DigitalAgencyPrimitiveColor.Sumi400,
  textPlaceHolder = DigitalAgencyPrimitiveColor.Sumi500,
  textOnFill = DigitalAgencyPrimitiveColor.white,
  textLink = DigitalAgencyPrimitiveColor.Sea300,
  textHover = DigitalAgencyPrimitiveColor.Sea200,
  textActive = DigitalAgencyPrimitiveColor.Sea200,
  textVisited = DigitalAgencyPrimitiveColor.Sea200,
  textAlert = DigitalAgencyPrimitiveColor.Sun500,
  textDisabled = DigitalAgencyPrimitiveColor.Sumi600,
  iconLabel = DigitalAgencyPrimitiveColor.white,
  iconActive = DigitalAgencyPrimitiveColor.Sea300,
  iconAlert = DigitalAgencyPrimitiveColor.Sun500,
  iconDisabled = DigitalAgencyPrimitiveColor.Sumi600,
  buttonNormal = DigitalAgencyPrimitiveColor.Sea300,
  buttonHover = DigitalAgencyPrimitiveColor.Sea300.copy(alpha = 0.1f),
  buttonActive = DigitalAgencyPrimitiveColor.Sea300.copy(alpha = 0.1f),
  buttonDisabledBG = DigitalAgencyPrimitiveColor.Sumi500,
  borderField = DigitalAgencyPrimitiveColor.white,
  borderDivider = DigitalAgencyPrimitiveColor.Sumi700,
  borderFocused = DigitalAgencyPrimitiveColor.Wood600,
  borderSelected = DigitalAgencyPrimitiveColor.Sea300,
  borderAlert = DigitalAgencyPrimitiveColor.Sun500,
  borderDisabled = DigitalAgencyPrimitiveColor.Sumi300,
  statusSuccess = DigitalAgencyPrimitiveColor.Forest600,
  statusAlert = DigitalAgencyPrimitiveColor.Sun500,
  statusWarning = DigitalAgencyPrimitiveColor.Wood500,
  chartPrimary = DigitalAgencyPrimitiveColor.Sea100,
  chartSecondary = DigitalAgencyPrimitiveColor.Sea300,
)
