name: Build PullRequest

on:
  pull_request:
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # チェックアウト
      - name: Checkout Repository
        uses: actions/checkout@v2

      # JDKのセットアップ
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

        # コンパイル
      - name: Run Compile
        run: ./gradlew assembleDebug
